[workspace]
members = [
  # CLI game
  "doppelkopf-rs",
  # Lambda operations
  "get_new_game_id_lambda",
  "join_new_game_lambda",
  "deal_cards_lambda",
  "make_announcement_lambda",
  "play_trick_lambda",
  # Universal Libraries
  "doppelkopf_cards_lib"
]
resolver = "2"
