name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_requests:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout code
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry/
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: | ${{ runner.os }}-cargo-build-

      - name: Cache Cargo build
        uses: actions/cache@v2
        with:
          path: ~/.cargo/build/
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: | ${{ runner.os }}-cargo-build-

      - name: Build
        run: cargo build --verbose

      - name: Run unit tests
        run: cargo test --verbose

      - name: Run clippy
        run: cargo clippy

      - name: Build and deploy (conditional)
        if: github.ref == 'refs/head/main' && success()
        run: | echo "Build and deploy process here"
